package codeSpitters.programathon_2018.model;
// Generated Sep 22, 2018 8:14:08 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AntecedentDocument generated by hbm2java
 */
@Entity
@Table(name="ANTECEDENT_DOCUMENT"
    ,catalog="CODE_SPITTERS"
)
public class AntecedentDocument  implements java.io.Serializable {


     private Integer id;
     private Antecedent antecedent;
     private byte[] document;
     private String mimeType;
     private String description;
     private String name;
     private String source;

    public AntecedentDocument() {
    }

	
    public AntecedentDocument(byte[] document, String mimeType) {
        this.document = document;
        this.mimeType = mimeType;
    }
    public AntecedentDocument(Antecedent antecedent, byte[] document, String mimeType, String description, String name, String source) {
       this.antecedent = antecedent;
       this.document = document;
       this.mimeType = mimeType;
       this.description = description;
       this.name = name;
       this.source = source;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ANTECEDENT_ID")
    public Antecedent getAntecedent() {
        return this.antecedent;
    }
    
    public void setAntecedent(Antecedent antecedent) {
        this.antecedent = antecedent;
    }

    
    @Column(name="DOCUMENT", nullable=false)
    public byte[] getDocument() {
        return this.document;
    }
    
    public void setDocument(byte[] document) {
        this.document = document;
    }

    
    @Column(name="MIME_TYPE", nullable=false, length=50)
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    
    @Column(name="DESCRIPTION", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="NAME", length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="SOURCE", length=40)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }




}


