package codeSpitters.programathon_2018.model;
// Generated Sep 22, 2018 8:14:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Antecedent generated by hbm2java
 */
@Entity
@Table(name="ANTECEDENT"
    ,catalog="CODE_SPITTERS"
)
public class Antecedent  implements java.io.Serializable {


     private Integer id;
     private Children children;
     private String disease;
     private int durationDays;
     private String treatment;
     private String medicine;
     private Set antecedentDocuments = new HashSet(0);
     private Date date;

    public Antecedent() {
    }

	
    public Antecedent(Children children, String disease, int durationDays, String treatment, String medicine) {
        this.children = children;
        this.disease = disease;
        this.durationDays = durationDays;
        this.treatment = treatment;
        this.medicine = medicine;
    }
    public Antecedent(Children children, String disease, int durationDays, String treatment, String medicine, Date date, Set antecedentDocuments) {
       this.children = children;
       this.disease = disease;
       this.durationDays = durationDays;
       this.treatment = treatment;
       this.antecedentDocuments = antecedentDocuments;
       this.date = date;
       this.medicine = medicine;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CHILDREN_SSN", nullable=false)
    public Children getChildren() {
        return this.children;
    }
    
    public void setChildren(Children children) {
        this.children = children;
    }

    
    @Column(name="DISEASE", nullable=false, length=65535)
    public String getDisease() {
        return this.disease;
    }
    
    public void setDisease(String disease) {
        this.disease = disease;
    }

    
    @Column(name="DURATION_DAYS", nullable=false)
    public int getDurationDays() {
        return this.durationDays;
    }
    
    public void setDurationDays(int durationDays) {
        this.durationDays = durationDays;
    }

    
    @Column(name="TREATMENT", nullable=false, length=65535)
    public String getTreatment() {
        return this.treatment;
    }
    
    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    @Column(name="MEDICINE", length=30)
    public String getMedicine() {
        return this.medicine;
    }

    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="antecedent")
    public Set getAntecedentDocuments() {
        return this.antecedentDocuments;
    }
    
    public void setAntecedentDocuments(Set antecedentDocuments) {
        this.antecedentDocuments = antecedentDocuments;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", length=19)
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }


}


