package codeSpitters.programathon_2018.model;
// Generated Sep 22, 2018 8:14:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Children generated by hbm2java
 */
@Entity
@Table(name="CHILDREN"
    ,catalog="CODE_SPITTERS"
)
public class Children  implements java.io.Serializable {


     private String ssn;
     private Responsible responsible;
     private String fullName;
     private String status;
     private int age;
     private String gender;
     private String ethnicGroup;
     private String responsibleRelation;
     private Set antecedents = new HashSet(0);
     private Set medicalCases = new HashSet(0);
     private Set dailyPhysicalStatuses = new HashSet(0);

    public Children() {
    }

	
    public Children(String ssn, Responsible responsible, String fullName, int age, String gender, String ethnicGroup, String responsibleRelation) {
        this.ssn = ssn;
        this.responsible = responsible;
        this.fullName = fullName;
        this.age = age;
        this.gender = gender;
        this.ethnicGroup = ethnicGroup;
        this.responsibleRelation = responsibleRelation;
    }
    public Children(String ssn, Responsible responsible, String fullName, int age, String gender, String ethnicGroup, String responsibleRelation, Set antecedents, Set medicalCases, Set dailyPhysicalStatuses) {
       this.ssn = ssn;
       this.responsible = responsible;
       this.fullName = fullName;
       this.age = age;
       this.gender = gender;
       this.ethnicGroup = ethnicGroup;
       this.responsibleRelation = responsibleRelation;
       this.antecedents = antecedents;
       this.medicalCases = medicalCases;
       this.dailyPhysicalStatuses = dailyPhysicalStatuses;
    }
   
     @Id 

    
    @Column(name="SSN", unique=true, nullable=false, length=35)
    public String getSsn() {
        return this.ssn;
    }
    
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESPONSIBLE_SSN", nullable=false)
    public Responsible getResponsible() {
        return this.responsible;
    }
    
    public void setResponsible(Responsible responsible) {
        this.responsible = responsible;
    }

    
    @Column(name="FULL_NAME", nullable=false, length=35)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Column(name="STATUS", nullable=true, length=100)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="AGE", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    
    @Column(name="GENDER", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="ETHNIC_GROUP", nullable=false, length=50)
    public String getEthnicGroup() {
        return this.ethnicGroup;
    }
    
    public void setEthnicGroup(String ethnicGroup) {
        this.ethnicGroup = ethnicGroup;
    }

    
    @Column(name="RESPONSIBLE_RELATION", nullable=false, length=10)
    public String getResponsibleRelation() {
        return this.responsibleRelation;
    }
    
    public void setResponsibleRelation(String responsibleRelation) {
        this.responsibleRelation = responsibleRelation;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="children")
    public Set getAntecedents() {
        return this.antecedents;
    }
    
    public void setAntecedents(Set antecedents) {
        this.antecedents = antecedents;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="children")
    public Set getMedicalCases() {
        return this.medicalCases;
    }
    
    public void setMedicalCases(Set medicalCases) {
        this.medicalCases = medicalCases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="children")
    public Set getDailyPhysicalStatuses() {
        return this.dailyPhysicalStatuses;
    }
    
    public void setDailyPhysicalStatuses(Set dailyPhysicalStatuses) {
        this.dailyPhysicalStatuses = dailyPhysicalStatuses;
    }




}


