package codeSpitters.programathon_2018.model;
// Generated Sep 22, 2018 8:14:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Responsible generated by hbm2java
 */
@Entity
@Table(name="RESPONSIBLE"
    ,catalog="CODE_SPITTERS"
)
public class Responsible  implements java.io.Serializable {


     private String userSsn;
     private User user;
     private Set childrens = new HashSet(0);

    public Responsible() {
    }

	
    public Responsible(User user) {
        this.user = user;
    }
    public Responsible(User user, Set childrens) {
       this.user = user;
       this.childrens = childrens;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="user"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="USER_SSN", unique=true, nullable=false, length=35)
    public String getUserSsn() {
        return this.userSsn;
    }
    
    public void setUserSsn(String userSsn) {
        this.userSsn = userSsn;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="responsible")
    public Set getChildrens() {
        return this.childrens;
    }
    
    public void setChildrens(Set childrens) {
        this.childrens = childrens;
    }




}


