package codeSpitters.programathon_2018.model;
// Generated Sep 22, 2018 8:14:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Symptom generated by hbm2java
 */
@Entity
@Table(name="SYMPTOM"
    ,catalog="CODE_SPITTERS"
)
public class Symptom  implements java.io.Serializable {


     private Integer id;
     private MedicalCase medicalCase;
     private Date date;
     private String physicalStatus;
     private String description;
     private String source;
     private Set symptomPhotos = new HashSet(0);

    public Symptom() {
    }

	
    public Symptom(Date date) {
        this.date = date;
    }
    public Symptom(MedicalCase medicalCase, Date date, String physicalStatus, String description, String source, Set symptomPhotos) {
       this.medicalCase = medicalCase;
       this.date = date;
       this.physicalStatus = physicalStatus;
       this.description = description;
       this.source = source;
       this.symptomPhotos = symptomPhotos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MEDICAL_CASE_ID")
    public MedicalCase getMedicalCase() {
        return this.medicalCase;
    }
    
    public void setMedicalCase(MedicalCase medicalCase) {
        this.medicalCase = medicalCase;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="PHYSICAL_STATUS", length=100)
    public String getPhysicalStatus() {
        return this.physicalStatus;
    }
    
    public void setPhysicalStatus(String physicalStatus) {
        this.physicalStatus = physicalStatus;
    }

    
    @Column(name="DESCRIPTION", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="SOURCE", length=40)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="symptom")
    public Set getSymptomPhotos() {
        return this.symptomPhotos;
    }
    
    public void setSymptomPhotos(Set symptomPhotos) {
        this.symptomPhotos = symptomPhotos;
    }




}


