package codeSpitters.programathon_2018.service.mail;

import javax.mail.Transport;

public class NotificationFormats {

    public static String prepareDailyNotification(String responsibleName, String childName) {
        return "<html>\n"
                + "\n"
                + "<head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <link href=\"http://fonts.googleapis.com/css?family=Roboto\" rel=\"stylesheet\" type=\"text/css\"/>\n"
                + "    <meta meta=\"Content-Type\" content=\"text/html\" />\n"
                + "    <style>\n"
                + "        html {\n"
                + "            width: 100%;\n"
                + "            margin: 0px;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "            line-height: 1.5;\n"
                + "            font-family: Roboto, sans-serif;\n"
                + "            font-weight: 400;\n"
                + "            font-size: 15px;\n"
                + "            color: #000000;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            width: 90%;\n"
                + "            max-width: 600px;\n"
                + "            margin: auto;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "        }\n"
                + "\n"
                + "        table,\n"
                + "        tbody {\n"
                + "            width: 100%;\n"
                + "            margin: 0px;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "        }\n"
                + "\n"
                + "        tr {\n"
                + "            width: 100%;\n"
                + "            margin: 0px;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "            margin: 50px auto;\n"
                + "        }\n"
                + "\n"
                + "        td {\n"
                + "            width: 100%;\n"
                + "            margin: 0px;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "        }\n"
                + "\n"
                + "        .logo-artes {\n"
                + "            margin-right: auto;\n"
                + "            margin-left: auto;\n"
                + "            margin-top: 50px;\n"
                + "            height: auto;\n"
                + "            min-width: 200px;\n"
                + "            max-width: 300px;\n"
                + "            width: 40%;\n"
                + "        }\n"
                + "\n"
                + "        img {\n"
                + "            width: 50px;\n"
                + "            margin: -18px 5px;\n"
                + "        }\n"
                + "\n"
                + "        .informacion {\n"
                + "            width: auto;\n"
                + "            margin: 5px;\n"
                + "        }\n"
                + "\n"
                + "        .informacion td {\n"
                + "            text-align: left;\n"
                + "        }\n"
                + "\n"
                + "        @media only screen and (min-width: 525px) {\n"
                + "            footer {\n"
                + "                width: 100%;\n"
                + "                display: inline-flex;\n"
                + "            }\n"
                + "\n"
                + "            .left {\n"
                + "                width: 50%;\n"
                + "                text-align: left;\n"
                + "                display: inline-flex;\n"
                + "                padding: 0px 5px;\n"
                + "            }\n"
                + "\n"
                + "            .left p,\n"
                + "            .left a {\n"
                + "                width: auto;\n"
                + "                margin: 0px;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right {\n"
                + "                width: 50%;\n"
                + "                float: right;\n"
                + "                padding: 0px 5px;\n"
                + "            }\n"
                + "\n"
                + "            .right div {\n"
                + "                display: inline-flex;\n"
                + "                float: right;\n"
                + "            }\n"
                + "\n"
                + "            .right div p,\n"
                + "            .right div a {\n"
                + "                width: auto;\n"
                + "                margin: 0px;\n"
                + "                text-align: right;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right div a,\n"
                + "            .left a {\n"
                + "                margin-left: 5px;\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "\n"
                + "        @media only screen and (max-width: 524px) {\n"
                + "            footer {\n"
                + "                width: 100%;\n"
                + "                display: block;\n"
                + "            }\n"
                + "\n"
                + "            .left {\n"
                + "                width: 100%;\n"
                + "                text-align: center;\n"
                + "                display: block;\n"
                + "                padding: 0px;\n"
                + "                margin: 20px auto;\n"
                + "            }\n"
                + "\n"
                + "            .left p,\n"
                + "            .left a {\n"
                + "                width: auto;\n"
                + "                margin: 0px;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right {\n"
                + "                width: 100%;\n"
                + "                text-align: center;\n"
                + "                display: block;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right div {\n"
                + "                display: inline-flex;\n"
                + "            }\n"
                + "\n"
                + "            .right div p,\n"
                + "            .right div a {\n"
                + "                width: auto;\n"
                + "                margin: 0px;\n"
                + "                text-align: center;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right div a,\n"
                + "            .left a {\n"
                + "                margin-left: 5px;\n"
                + "            }\n"
                + "        }\n"
                + "        \n"
                + "        a{\n"
                + "            text-decoration: none;\n"
                + "            color: #26c2f2;\n"
                + "        }\n"
                + "        \n"
                + "        a:hover{\n"
                + "            text-decoration: none;\n"
                + "            color: #CCC\n"
                + "        }\n"
                + "        \n"
                + "        h1, h2{\n"
                + "            color: #636567;\n"
                + "            font-weight: bold;\n"
                + "        }\n"
                + "\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "    <table>\n"
                + "        <tr>\n"
                + "            <td style=\"text-align: left;\">\n"
                + "                <h1>Recordatorio de seguimiento de síntomas</h1>\n"
                + "                <h2>Recordatorio diario</h2>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "        <tr>\n"
                + "            <td style=\"text-align: left;\">\n"
                + "                <p>Estimad@ " + responsibleName +", porfavor recerde recordar los síntomas de: " + childName + "</p>\n"
                + "                <p>Esa información es importante para el monitoreo de síntomas</p>\n"
                + "                <p>Muchas Gracias</p>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "        <tr>\n"
                + "            <td style=\"display: inline-flex !important;\">\n"
                + "                <footer>\n"
                + "                    <div class=\"left\">\n"
                + "                        <p id=\"developby\">Desarrollado por Code Spitters</p>\n"
                + "                    </div>\n"
                + "                    <div class=\"right\">\n"
                + "                        <div>\n"
                + "                            <p>2018 Programathon</p>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                </footer>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "    </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";
    }

    public static String prepareFinalNotification(String responsibleName, String childName) {
        return "<html>\n"
                + "\n"
                + "<head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width\" />\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <link href=\"http://fonts.googleapis.com/css?family=Roboto\" rel=\"stylesheet\" type=\"text/css\"/>\n"
                + "    <meta meta=\"Content-Type\" content=\"text/html\" />\n"
                + "    <style>\n"
                + "        html {\n"
                + "            width: 100%;\n"
                + "            margin: 0px;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "            line-height: 1.5;\n"
                + "            font-family: Roboto, sans-serif;\n"
                + "            font-weight: 400;\n"
                + "            font-size: 15px;\n"
                + "            color: #000000;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            width: 90%;\n"
                + "            max-width: 600px;\n"
                + "            margin: auto;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "        }\n"
                + "\n"
                + "        table,\n"
                + "        tbody {\n"
                + "            width: 100%;\n"
                + "            margin: 0px;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "        }\n"
                + "\n"
                + "        tr {\n"
                + "            width: 100%;\n"
                + "            margin: 0px;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "            margin: 50px auto;\n"
                + "        }\n"
                + "\n"
                + "        td {\n"
                + "            width: 100%;\n"
                + "            margin: 0px;\n"
                + "            padding: 0px;\n"
                + "            text-align: center;\n"
                + "            display: block;\n"
                + "        }\n"
                + "\n"
                + "        .logo-artes {\n"
                + "            margin-right: auto;\n"
                + "            margin-left: auto;\n"
                + "            margin-top: 50px;\n"
                + "            height: auto;\n"
                + "            min-width: 200px;\n"
                + "            max-width: 300px;\n"
                + "            width: 40%;\n"
                + "        }\n"
                + "\n"
                + "        img {\n"
                + "            width: 50px;\n"
                + "            margin: -18px 5px;\n"
                + "        }\n"
                + "\n"
                + "        .informacion {\n"
                + "            width: auto;\n"
                + "            margin: 5px;\n"
                + "        }\n"
                + "\n"
                + "        .informacion td {\n"
                + "            text-align: left;\n"
                + "        }\n"
                + "\n"
                + "        @media only screen and (min-width: 525px) {\n"
                + "            footer {\n"
                + "                width: 100%;\n"
                + "                display: inline-flex;\n"
                + "            }\n"
                + "\n"
                + "            .left {\n"
                + "                width: 50%;\n"
                + "                text-align: left;\n"
                + "                display: inline-flex;\n"
                + "                padding: 0px 5px;\n"
                + "            }\n"
                + "\n"
                + "            .left p,\n"
                + "            .left a {\n"
                + "                width: auto;\n"
                + "                margin: 0px;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right {\n"
                + "                width: 50%;\n"
                + "                float: right;\n"
                + "                padding: 0px 5px;\n"
                + "            }\n"
                + "\n"
                + "            .right div {\n"
                + "                display: inline-flex;\n"
                + "                float: right;\n"
                + "            }\n"
                + "\n"
                + "            .right div p,\n"
                + "            .right div a {\n"
                + "                width: auto;\n"
                + "                margin: 0px;\n"
                + "                text-align: right;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right div a,\n"
                + "            .left a {\n"
                + "                margin-left: 5px;\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "\n"
                + "        @media only screen and (max-width: 524px) {\n"
                + "            footer {\n"
                + "                width: 100%;\n"
                + "                display: block;\n"
                + "            }\n"
                + "\n"
                + "            .left {\n"
                + "                width: 100%;\n"
                + "                text-align: center;\n"
                + "                display: block;\n"
                + "                padding: 0px;\n"
                + "                margin: 20px auto;\n"
                + "            }\n"
                + "\n"
                + "            .left p,\n"
                + "            .left a {\n"
                + "                width: auto;\n"
                + "                margin: 0px;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right {\n"
                + "                width: 100%;\n"
                + "                text-align: center;\n"
                + "                display: block;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right div {\n"
                + "                display: inline-flex;\n"
                + "            }\n"
                + "\n"
                + "            .right div p,\n"
                + "            .right div a {\n"
                + "                width: auto;\n"
                + "                margin: 0px;\n"
                + "                text-align: center;\n"
                + "                padding: 0px;\n"
                + "            }\n"
                + "\n"
                + "            .right div a,\n"
                + "            .left a {\n"
                + "                margin-left: 5px;\n"
                + "            }\n"
                + "        }\n"
                + "        \n"
                + "        a{\n"
                + "            text-decoration: none;\n"
                + "            color: #26c2f2;\n"
                + "        }\n"
                + "        \n"
                + "        a:hover{\n"
                + "            text-decoration: none;\n"
                + "            color: #CCC\n"
                + "        }\n"
                + "        \n"
                + "        h1, h2{\n"
                + "            color: #636567;\n"
                + "            font-weight: bold;\n"
                + "        }\n"
                + "\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "    <table>\n"
                + "        <tr>\n"
                + "            <td style=\"text-align: left;\">\n"
                + "                <h1>Recordatorio de seguimiento de síntomas</h1>\n"
                + "                <h2>Recordatorio diario</h2>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "        <tr>\n"
                + "            <td style=\"text-align: left;\">\n"
                + "                <p>Estimad@ " + responsibleName +", usted ha pasado 14 días sin brindar información sobre " + childName + "</p>\n"
                + "                <p>Por esta razón se dejará de notificarle recordatorios sobre el monitoreo de síntomas</p>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "        <tr>\n"
                + "            <td style=\"display: inline-flex !important;\">\n"
                + "                <footer>\n"
                + "                    <div class=\"left\">\n"
                + "                        <p id=\"developby\">Desarrollado por Code Spitters</p>\n"
                + "                    </div>\n"
                + "                    <div class=\"right\">\n"
                + "                        <div>\n"
                + "                            <p>2018 Programathon</p>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                </footer>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "    </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";
    }


}